[package]
name = "findata-app"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "findata-app"
path = "src/main.rs"

[dependencies]
findata = { path = "../findata" }
findata-ext = { path = "../findata-ext" }
axum = { version = "0.7", features = ["macros", "ws", "multipart"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal", "net"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1"
redis = { version = "0.27", default-features = false, features = ["tokio-comp"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "stream"] }
